openapi: 3.0.0
info:
  title: Lumen Template API
  version: '1.0'
  description: An example API
  contact:
    name: Floris Cornel
  license:
    name: MIT
servers:
  - url: 'http://localhost:5501'
    description: Docker Compose
paths:
  /v1/posts:
    get:
      summary: Get Posts
      tags:
        - v1
      responses:
        '200':
          $ref: '#/components/responses/PostPagination'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      operationId: get-v1-posts
      description: 'List, search and filter posts.'
      parameters:
        - $ref: '#/components/parameters/search'
    parameters: []
    post:
      summary: Create Post
      operationId: post-v1-posts
      requestBody:
        $ref: '#/components/requestBodies/PostCreate'
      responses:
        '201':
          $ref: '#/components/responses/PostResource'
        '401':
          $ref: '#/components/responses/Forbidden'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/PostValidationError'
      description: Create a new post
      tags:
        - v1
  '/v1/posts/{id}':
    get:
      summary: Get Post
      tags:
        - v1
      responses:
        '200':
          $ref: '#/components/responses/PostResource'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      operationId: get-v1-posts-id
      description: Get a single Post by their UUID.
    parameters:
      - $ref: '#/components/parameters/id'
    post:
      summary: Update Post
      operationId: post-v1-posts-id
      responses:
        '202':
          $ref: '#/components/responses/PostResource'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/PostValidationError'
      description: Make changes to a Post.
      requestBody:
        $ref: '#/components/requestBodies/PostUpdate'
      tags:
        - v1
    delete:
      summary: Delete Post
      operationId: delete-v1-posts-id
      responses:
        '202':
          description: Accepted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      description: Delete a post
      tags:
        - v1
components:
  schemas:
    Post:
      title: Post
      type: object
      description: A blog post created by a user
      examples:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          title: 12 Amazing Facts About Stroopwafels
          slug: 12-amazing-facts-about-stroopwafels
          content: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          format: uuid
          description: UUID of the post
        title:
          type: string
          description: Title of the post
          example: 12 Amazing Facts About Stroopwafels
        slug:
          type: string
          description: Unique slug used in the post URL
          example: 12-amazing-facts-about-stroopwafels
        content:
          type: string
          description: Content formatted as markdown.
          example: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
        created_at:
          type: string
          format: date-time
          description: ISO string of creation of post
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - slug
        - content
        - created_at
        - updated_at
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
  responses:
    PostPagination:
      description: Response containing a list of Posts and metadata.
      content:
        application/json:
          schema:
            type: object
            properties:
              current_page:
                type: integer
                example: 1
                minimum: 0
              per_page:
                type: number
                example: 15
                minimum: 0
              total_count:
                type: integer
                minimum: 0
                example: 32
              total_pages:
                type: integer
                example: 3
                minimum: 0
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
            required:
              - current_page
              - per_page
              - total_count
              - total_pages
              - data
          examples:
            example-list:
              value:
                current_page: 1
                per_page: 15
                total_count: 32
                total_pages: 3
                data:
                  - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    title: 12 Amazing Facts About Stroopwafels
                    slug: 12-amazing-facts-about-stroopwafels
                    content: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
    Unauthorized:
      description: API Token is invalid.
      content:
        text/html:
          schema:
            type: string
            example: Unauthorized.
          examples:
            Unauthorized.:
              value: Unauthorized.
    Forbidden:
      description: This action is forbidden for the current user.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: This action is unauthorized.
          examples:
            unauthorized:
              value:
                message: This action is unauthorized.
    NotFound:
      description: Resource with this ID was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          examples:
            post-not-found:
              value:
                message: 'No query results for model [App\Models\Post] 5cbae37d-0ef8-43ee-a189-373c98e3ec8b'
    PostResource:
      description: Response containing a single post.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Post'
          examples:
            example-post:
              value:
                id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                title: 12 Amazing Facts About Stroopwafels
                slug: 12-amazing-facts-about-stroopwafels
                content: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
                created_at: '2019-08-24T14:15:22Z'
                updated_at: '2019-08-24T14:15:22Z'
    PostValidationError:
      description: Validation error for Post input data.
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: array
                items:
                  type: string
                  example: The title field is required.
              slug:
                type: array
                items:
                  type: string
                  example: The slug has already been taken.
              content:
                type: array
                example: null
                items:
                  type: string
          examples:
            slug-uniqueness-error:
              value:
                slug:
                  - The slug has already been taken.
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
        example: 6a5ada60-8f2d-3c0c-865e-1c7e6eb3f359
        pattern: '\b[0-9a-f]{8}(\b-[0-9a-f]{4}){3}-\b[0-9a-f]{12}\b'
      description: lowercase uuid
    search:
      name: search
      in: query
      required: false
      schema:
        type: string
        example: Stroopwafels
      description: Search query
  requestBodies:
    PostCreate:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                maxLength: 255
                minLength: 1
                example: 12 Amazing Facts About Stroopwafels
                description: Title of the Post
              slug:
                type: string
                minLength: 1
                maxLength: 50
                pattern: '^[a-z0-9][a-z0-9\-]+'
                example: 12-amazing-facts-about-stroopwafels
                description: 'URL slug, allowed characters: ''a-z'', ''0-9'' and ''-'' '
              content:
                type: string
                minLength: 1
                maxLength: 1000
                example: '## Introduction\\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\\n3. ...'
                description: Content of the blog post in Markdown format
            required:
              - title
              - slug
              - content
          examples:
            post-create-example:
              value:
                title: 12 Amazing Facts About Stroopwafels
                slug: 12-amazing-facts-about-stroopwafels
                content: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
      description: Post creation input
    PostUpdate:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                maxLength: 255
                minLength: 1
                example: 12 Amazing Facts About Stroopwafels
                description: Title of the Post
              slug:
                type: string
                minLength: 1
                maxLength: 50
                pattern: '^[a-z0-9][a-z0-9\-]+'
                example: 12-amazing-facts-about-stroopwafels
                description: 'URL slug, allowed characters: ''a-z'', ''0-9'' and ''-'' '
              content:
                type: string
                minLength: 1
                maxLength: 1000
                example: '## Introduction\\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\\n3. ...'
                description: Content of the blog post in Markdown format
          examples:
            post-create-example:
              value:
                title: 12 Amazing Facts About Stroopwafels
                slug: 12-amazing-facts-about-stroopwafels
                content: '## Introduction\nIf you''ve ever eaten a stoopwafel before, you will be very surprised to hear these facts:\n1. One stroopwafel contains the same amount of calories as 2 Oreos.\n2. They were first made in the town of Gouda in the Netherlands, in 1784.\n3. ...'
      description: Post creation input
  examples: {}
security:
  - AccessToken: []
tags:
  - name: v1
