name: PHPUnit

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: carlosabcs/lumen-phpunit-action@master