name: PHPUnit

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: ./phpunit.xml
        memory_limit: 256M